---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Belgrade
  METALLB_LB_RANGE: 10.5.0.210-10.5.0.240
  METALLB_K8S_GATEWAY_ADDR: 10.5.0.211
  METALLB_TRAEFIK_ADDR: 10.5.0.212
  SVC_NGINX_ADDR: 10.5.0.213
  SVC_PLEX_IP: 10.5.0.221
  SVC_HASS_IP: 10.5.0.222
  SVC_MQTT_IP: 10.5.0.223
  SVC_PIHOLE_IP: 10.5.0.224
  SVC_UNBOUND_IP: 10.5.0.225
  SVC_QBIT_IP: 10.5.0.226
  SVC_LOKI_IP: 10.5.0.227
  SVC_OMADA_IP: 10.5.0.228
  SVC_GITEA_IP: 10.5.0.229
