---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - flux-system
  - kube-system
  - networking
  - media
  - home
  - monitoring
  - democratic-csi
  # - kasten
  # - system-upgrade
